### ISSUE TITLE
Strange behavior when publishing pages with uncommitted pieces on them

### ISSUE THREAD

**Issue by agilbert** [punkave/apostrophe-workflow#35]
add a new image to an image widget on a page
save but don't commit the image
publish the changes on the page
go to the live version of the page
no image!

What should the sensible behavior be for this situation?

**Comment by boutell** [comment]
I think this might well be the sensible behavior, although a nice upgrade would be to visually flag any joined resources that are published only in draft. Should probably happen after we get the live flag in there in the first place to replace using "published" for this purpose.
