### ISSUE TITLE
Style schema field workflow

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe-workflow#6]
Currently a rough live / draft toggle and revert button. Should be nice. Functionality might be a little different from Stuart's design.

**Comment by stuartromanek** [comment]
I have some improvements to the UI for this but I'm having trouble with the way schema elements are being disabled when in LIVE mode, I can't get my new `<select>` element to be left alone

https://github.com/punkave/apostrophe-workflow/blob/schema-styles/public/js/schemas.js#L122

any insight on that @boutell ?
