### ISSUE TITLE
Style workflow's submitted content modal

### ISSUE THREAD

**Issue by boutell** [punkave/apostrophe-workflow#7]
This is probably going to remain a very simple list of doc titles, but it should be a nice one. This is what you access by clicking "workflow" in the admin bar; it shows you stuff someone clicked submit on, which you have permission to commit.

**Comment by agilbert** [comment]
@boutell I am trying to generate some submissions as the admin user on the sandbox. I click the `Submit` button and says my submission will be reviewed, but nothing appears in the list. Does it not actually create a submission from admin accounts? Might there be another bug here?

I tried creating an account for a new user on the sandbox and gave it the "Edit" permission. But when I log in as this user I don't have any editing UI.

**Comment by boutell** [comment]
that’s odd, it worked for me last I tried it. It’s just setting a flag property on the doc. Let me try it again.

**Comment by boutell** [comment]
That bug is fixed.
