### ISSUE TITLE
Images availability issues

### ISSUE THREAD

**Issue by ThierryDatawords** [punkave/apostrophe-workflow#80]
Hello there! 

Sandbox: http://workflowsandbox.punkave.net/

Are are the steps:

- I added 2 components on the sandbox's homepage (default locale): a picture and a video (painting and elephants).
- I committed and exported to all locales (you can check it on 'fr' locale).
- Then, back on the default locale, I changed the picture and video URL (Tom and scuba diver).
- I committed and exported everywhere except fr locale.

-> The default locale is OK but the others are KO since the picture seems to have disappeared (the video is OK).

**Comment by ThierryDatawords** [comment]
Since I can't select an assignee: @boutell

**Comment by ThierryDatawords** [comment]
I think I found the origin of the issue: it seems that an asset doesn't automatically duplicate on other locales DAMs when exporting some changes. 
In our current case, the image depicting Tom has been uploaded from 'default' locale which explains why it's displaying fine. But if you check the DAM on other locales, the Tom image doesn't exists.

**Comment by boutell** [comment]
Hello Thierry,

When  you add an image you have the option to export the image itself as well. You will need to do that before it can appear in other locales.

So I'm going to close this issue, but you can reopen it if that feature is not working for you when you pursue it.
