### ISSUE TITLE
Add notification so that it is clear there is an implicit save operation happening before you commit, export, etc. via the "workflow" menu of pieces / pages

### ISSUE THREAD

**Issue by bobclewell** [punkave/apostrophe-workflow#88]
###  Steps
1. In Draft Mode
2. Click on “Page Menu" / "New Page”
3. Click "Workflow" / "Commit"
4. Click “Cancel”

### Actual
* The commit dialog closes (expected)
* The page dialog closes (unexpected)
* The new page gets created (unexpected)*

### Expected
* It should close the commit dialog and do nothing else.

### Note
* If you do steps 1 & 2 above, but then cancel out of the New Page dialog, that new page does NOT get created.

**Comment by boutell** [comment]
Per discussion this is not a bug but Bob is adding a notification. There must be a save operation before export, commit, etc. are possible, so it happens right away before you make those choices. However it's visually unclear because of the way modal unstacking occurs in the interface.

**Comment by bobclewell** [comment]
@boutell please see the PR: https://github.com/punkave/apostrophe-workflow/pull/90

**Comment by bobclewell** [comment]
Resolved with the above PR.
